pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

def remoteBuildCache = file("$settingsDir/../../config/gradle/remote-build-cache.settings.gradle")
if (remoteBuildCache.exists()) {
    apply from: remoteBuildCache
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            name "IMG.LY Artifactory"
            url "https://maven.img.ly/maven"
            mavenContent {
                includeGroup("ly.img")
            }
        }
        exclusiveContent {
            forRepository {
                ivy {
                    name = 'BundleTool releases'
                    url = 'https://github.com/google/bundletool/releases/download/'
                    patternLayout {
                        artifact '[revision]/[module](-[classifier])-[revision](.[ext])'
                    }
                    metadataSources {
                        artifact()
                    }
                }
            }
            filter {
                includeGroup('bundletool-github')
            }
        }
    }
}

rootProject.name = "CE.SDK Android Showcases"
include ':showcases-app'

if (file('internal.settings.gradle').exists()) {
    apply from: 'internal.settings.gradle'
}
